language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk: openjdk8

sudo: false

script:
  - set -e
  - sbt checkHeaders
  - sbt coverage doc test tut
  - sbt coverageReport
  - sbt clean transferPublishAndTagResources
  - scripts/publishAndTag 'slamdata/matryoshka'

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
