language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk: openjdk8

sudo: false

env:
  global:
    # ENCRYPTION_PASSWORD
    - secure: "tePXpEtuepKKOgy74lrZWd2AiBqwQs+akmEgWtmy/MIDZ2AO0Vq7zK6Obh+PyqGQq5jXvYonEyH5aci1QjVIPPZht1L3pa4xVJQbnV+yKNSDw/ZhORtZkoCrmxy+mT4KPZ0brEjiH307OOuKQsbJ3GqAM6tPw6cJ+/ToOJLU0uEN4Vx4OHcjbZPVhwQ4nwdfXbvsbFiyus1ptIJtULfv9uIUcZ3CnCeepPNW/qjdz0qV67eyZN27NcffRppqB3FZ/yMkQ7gbMAhbQ8M7OBmMCkL5MOPNlqxBq8o7yPTKfqP5gZ7WL/DBc7SX8ZqAuG2BFRskqos/pTn+UC71f+/rwserS3/+aHEHB2SGoMc9nfpwuXN/XUOrwfOH75Wvosxm5gNQ7VQtmK4Ja+Fux4kUSt9Ih0foqOC/Pp+rjaQ/VPoD4Iyn9vKBa5pB+4l4G/+xjE+i+7ECeF/YpZA3MpPEX8ZkAkcKAIXdV8BHgVS4dLVbx2rKNRgWhe/7F3w0ClPTeaQzdo52+oMJsNYBH7XPmbMZPKCLsLbtUrEPAmoVdfbWu+TWkK8CTgTIVdc7wjYCH3MXK9EUdTB4h4xfo0q4WljeuVYbyWHWVihqGv7oXjzReOcgK4WmnLpuMoImBMLYRsI1qwOgfe33AR6B9sDX6/caH6TdaeztNvqu3o7eHpw="
    # GITHUB_TOKEN
    - secure: "cT2XIZTDAgqtyZ4NFYyWJm982cqGFweLLt9lu3a/v78xMDnpinCxumeLdDEeY37PvGgy0ufo8CdD1LrnpTukQKn2+A1pp51MAqW9wtlgAi2TtL/hz3SawYwFURU5xpvM+SLYB5O59WkCUrbUtAiio+OSziuq3yMVEPtXprH6TPwjz1FAD58TKMZbjgF26OLFGpIe6ILkNk5Yj5p8EAFzyzsJkeCU5/dc+jZn1nLFYQ1tCDGpgfKWQnmo/X1M0AjWPdyI+K3UP86eL+utOC6u8ZG6yYHnKVmiBz1j5QuaGvX0Ca9L+Ye92dxv9+HvRM+lynY7hYjVJdcJ+zjqlC/nIH8LdAkmG3AfubKnykvLySYeJyDPwirO1urz3E07Koj/V4mTHu4UGNOxd8P2F/crJ88PQhppfvLcQawWLtPxlj7hP+Kav+JhUn6QGEHmQPK6gqI6rsS4R6bhFS0dw7rejhgAl/lMmnD6s5c57YqX575WPKerWazwCYQJI7vRFx4mxjFzYo0JD+18gSRnFTDPyvV8pJKhVgGGFzrjBTrK1ai/7zXKoA6vo+BAjaS+CKQvqLte4wYjkqekY8T6gOf4pig0fHRKDFO5Dq/p6oJ9ZUw9u0fyET1CqyVsYFn+Z9f9rSroZnPfEqplaixDrtQr4BGTsJE4pBMjbbFIl7oRR1E="
    # GITHUB_ACCESS_TOKEN
    - secure: "Ty02vEsyHB/mysS60SdY5onNg6q5DDbZy3ji6adNqDsDCDHd7Ckd3FWeYB3CBNqgAXvvu8fbthioCqQ646aUzkEnf+DHnwH3no8AYbqkvbDdRlBimYquDMjoZEH3NbGWLMkLzB2Uy9N1xs886SZnlAVrPNDJoVIw7vKmgI4JQuvSz9+JVek9nSzwlyN/FsqiUNz3NtxUEEuhLa3Yn49oCRcBjQyVhozFBaSBNfusOHZkxD1n4zCc0buJVGRYD8bmdigKjc7ySWM5RGB/XsRj7jlwxUBpCgY7enKqFtldo6Ou4ZZe0UuQWoKL7y2TZvd6OnU1hQdEtX1RuipQi153dpf0lir6dK2j2sJdfi5v8URQS1vIoGbI9lficDZKMzILDhQkOpYEVkc9HBH/ZsNO8G4emQeUMqpQHhzs3U4pL6yQw6kvKwvxlUjbrqzu9rNAnOiMtYhXdTKMEmW05SjVws769kF+Stn7YpTUeD7Sqli/BQo/RSgCH7BnyTjhr2ldESnvpnxLzDYxA1XmpHkoSJC7M6f5JcRszYDN3hwThqSZfXO/OxjE2QqFCZV9BwbLsJjhntHbNwr62aD59HrY1orb57Z3I1YBAaa19eMhJRX1qL016TgdNykxbmGCUX//m2A97kYuRa5xJnnh7WgzgLMxraxRFyww5z2HdHjdsO0="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "QvYkNzewShlLDOmns6xchkGh2nGg38vnAvfbTlsyEMd9h1YhLB0gkkzEWqsnLh33vIM0j5ga0UQ4t/4EY45oSXIgVeX/7tMMxaOd/ffbpw+6AKS7T6QQELKc25fZMEWZCiTUyBiO5XCP+st1g4kvj41DvAS44dgqJAVWE/Jfg+D/3g/Fvk/MSuu6YUyUg75koRA3OssqS2H2mNzRs0aWenPidK3KgbeiIH3bRv2CVMjWKY9chRrnO5F7QTgJYQhkO7deespmVzmEWwS9WfAfaP5CPz44Ku8M2SoiYae+mofwoCmASMYHAYtd+b9dDNtdjMN8wm1ayIveg19kigi4RChpBKOceIoRnZ8mltPqUXsluQ/XBof9iFdFnV8jSC2SfmS2CylQSJ4OYd+DdNrUjwynGpF6B6ribJmSLyz/PUZlXIPRs/LN55RIMLSNB25M+iyMGWuLbHJjmv9pU7FuImcZnf+cswcXFvSa0rZervWawbObbkw98SF9EqN9bFRKyqhb2tiXNs06cXt59UgV1+iMrfjlYxsaYAFU+HUO/QZIq5/zd7Hba+xxfL2c93/3I+i7pgXrRHxWv0cDluJUHZ3zSjTNP/feVxKjgxvFKk1byXd0nUrv0u/ZJgXOCtBzcQ2PLrxrUrP0xaI1QLw/6wXdZ5yDeHc28xzg+lAzhNk="
    - SBT=./sbt

script:
  - set -e
  - $SBT ++$TRAVIS_SCALA_VERSION checkHeaders test transferPublishAndTagResources
  - |-
    if [[ "$TRAVIS_SCALA_VERSION" =~ 2.12 ]]; then
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/matryoshka'
      fi
    fi

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
