language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk: openjdk8

sudo: false

script:
  - set -e
  - sbt checkHeaders test transferPublishAndTagResources
  - |-
    if [[ "$TRAVIS_SCALA_VERSION" =~ 2.12 ]]; then
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/matryoshka'
      fi
    fi

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
